name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          issue-labels: 'off-topic'
          issue-comment: >
            This repository does not accept bug reports for now,
            see discussions for details.
          pr-comment: >
            This repository does not accept pull requests for now,
            see discussions for details.
